seems to be working o_o

diff --git a/trash b/trash
--- a/trash
+++ b/trash
@@ -10,7 +10,7 @@
 #       list with parameters
 #       find a better way to create unique filenames
 
-mkdir ~/.trash
+mkdir -p ~/.trash
 shopt -s nullglob
 returnvalue=0
 
@@ -42,15 +42,16 @@ case "$1" in
   -l|--list)
     files=(~/.trash/*)
     [[ ${#files[*]} = 0 ]] && echo "Recycle bin is empty" >&2 && exit 2
-    echo "Id           Date                    Filename"
+    echo "  Id   | Date (YYYY-mm-dd HH:MM:SS) | Filename"
     num=0
     for file in ~/.trash/* ; do
-      filename="${file:67}" #remove metadata
+      file="${file##*/}"
+      filename="${file:61}" #remove metadata
       filename="$(base64 -d <<< "$filename")" #actual path+filename
       filename="${filename##*/}"
       datetime="${file:0:19}"
-      datetime="${datetime/-/ }"
-      printf "%05d     %s     %s\n" "$num" "$datetime" "$filename"
+      datetime="${datetime/_/ }"
+      printf "%06d |    %s     | %s\n" "$num" "$datetime" "$filename"
       ((num++))
     done
     ;;
@@ -60,22 +61,29 @@ case "$1" in
     files=(~/.trash/*)
     [[ ${#files[*]} = 0 ]] && echo "Recycle bin is empty" >&2 && exit 2
     shift
-    for (( i = 1; i < $#; i++ )) ; do
+    for (( i = 0; i < $#; i++ )) ; do
       if printf "%d" "$1" &> /dev/null ; then
         if [[ -n "${files[$1]}" ]] ; then
-          filename="${files[$1]}"
-          filename="${filename:67}"
+          filename="${files[$1]##*/}"
+          filename="${filename:61}"
           filename="$(base64 -d <<< "$filename")"
           directory="${filename%/*}"
           if [[ -d "$directory" ]] ; then
-            if ! mv "${files[$1]}" "$directory" 2> /dev/null ; then
-              tempfile="$(mktemp "/tmp/${files[$1]}-XXXXXX")"
+            if [[ -f "$directory/${filename##*/}" ]] ; then
+              tempfile="$(mktemp "/tmp/${files[$1]##*/}-XXXXXX")"
               echo "Couldn't restore $1 in its path, saved it in $tempfile" >&2
+              mv "${files[$1]}" "$tempfile"
+              returnvalue=8
+            elif ! mv "${files[$1]}" "$directory/${filename##*/}" 2> /dev/null ; then
+              tempfile="$(mktemp "/tmp/${files[$1]##*/}-XXXXXX")"
+              echo "Couldn't restore $1 in its path, saved it in $tempfile" >&2
+              mv "${files[$1]}" "$tempfile"
               returnvalue=6
             fi
           else
-            tempfile="$(mktemp "/tmp/${files[$1]}-XXXXXX")"
+            tempfile="$(mktemp "/tmp/${files[$1]##*/}-XXXXXX")"
             echo "Couldn't restore $1 in its path, saved it in $tempfile" >&2
+            mv "${files[$1]}" "$tempfile"
             returnvalue=7
           fi
         else
@@ -92,7 +100,7 @@ case "$1" in
   -c|--clean)
     if ! rm -rf ~/.trash/* ; then
       echo "Couldn't empty the trash bin" >&2
-      retunvalue=4
+      returnvalue=4
     fi
     ;;
 
@@ -100,21 +108,22 @@ case "$1" in
     shift ;&
 
   *)
-    for (( i = 1; i < $#; i++ )) ; do
+    for (( i = 0; i < $#; i++ )) ; do
       # hi, i'm an ugly hack, please kill me
-      if file="$(realpath -s "$2" 2> /dev/null)" ; then
-        read sha dummy <<< $(printf "$file" | sha1sum)
-        bfile=$(printf "$file" | base64)
-        datetime=$(date +%Y-%m-%d-%H-%M-%S)
-        if ! mv "$file" "$HOME/.trash/$datetime-$sha-$bfile" 2> /dev/null ; then
+      if file="$(realpath -s "$1" 2> /dev/null)" ; then
+        read sha dummy <<< $(printf %s "$file" | sha1sum)
+        bfile=$(printf %s "$file" | base64)
+        datetime=$(date +%Y-%m-%d_%H:%M:%S)
+        if mv "$file" "$HOME/.trash/$datetime-$sha-$bfile" 2> /dev/null ; then
+          :
         else
-          returnvalue=1
           echo "Couldn't move $file to trash" >&2
+          returnvalue=1
         fi
         shift
       else
-        returnvalue=1
-        echo "Couldn't read $2" >&2
+        echo "Couldn't read $1" >&2
+        returnvalue=9
       fi
     done
     ;;
